config/routes.rb
Rails.application.routes.draw do
  get 'first_entry_times/index'
  get 'slot_allocation_history/show'
  get 'used_slots/index'
  get 'slot_bookings/new'
  get 'slot_bookings/create'
  resources :slot_bookings
  root to: "slot_bookings#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry_point.rb
class EntryPoint < ApplicationRecord
  has_many :slot_bookings
end

app/models/parking_slot.rb
class ParkingSlot < ApplicationRecord
  has_many :slot_bookings
  belongs_to :entry_point
end

app/models/slot_booking.rb
# app/models/slot_booking.rb

class SlotBooking < ApplicationRecord
  belongs_to :parking_slot
  belongs_to :entry_point

  def self.find_nearest_available_slot(entry_point)
    available_slots = ParkingSlot.where.not(id: SlotBooking.select(:slot_id))

    nearest_slot = nil
    min_distance = nil

    available_slots.each do |slot|
      distance = Geocoder::Calculations.distance_between(
        [entry_point.latitude, entry_point.longitude],
        [slot.latitude, slot.longitude]
      )

      if min_distance.nil? || distance < min_distance
        nearest_slot = slot
        min_distance = distance
      end
    end

    nearest_slot
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/first_entry_times_controller.rb
class FirstEntryTimesController < ApplicationController
  def index
    @first_entries = SlotBooking.select('MIN(entry_time) as first_entry_time', :vehicle_registration_number).group(:vehicle_registration_number)
  end
end

app/controllers/slot_allocation_history_controller.rb
class SlotAllocationHistoryController < ApplicationController
  def show
    @vehicle_registration_number = params[:vehicle_registration_number]
    @allocation_history = SlotBooking.where(vehicle_registration_number: @vehicle_registration_number).order(entry_time: :asc)
  end
end

app/controllers/slot_bookings_controller.rb
class SlotBookingsController < ApplicationController
  before_action :set_entry_point
  def new
    @slot_booking = SlotBooking.new
  end

  def create
    @slot_booking = SlotBooking.new(slot_booking_params)

    entry_point = EntryPoint.find(@slot_booking.entrance_number)
    # Find the nearest available slot for the selected entry point

    @slot_booking.slot = SlotBooking.find_nearest_available_slot(entry_point)

    if @slot_booking.save
      flash[:success] = 'Slot booked successfully!'
      redirect_to root_path
    else
      flash.now[:error] = 'Slot booking failed!'
      render :new
    end
  end

  private

  def set_entry_point
    @entry_points = EntryPoint.all
  end

  def slot_booking_params
    params.require(:slot_booking).permit(:entrance_number, :vehicle_registration_number, :entry_time)
  end
end

app/controllers/used_slots_controller.rb
class UsedSlotsController < ApplicationController
  def index
    @selected_date = params[:selected_date] || Date.today
    @used_slots = SlotBooking.where(entry_time: @selected_date.beginning_of_day..@selected_date.end_of_day)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_entry_times_helper.rb
module FirstEntryTimesHelper
end

app/helpers/slot_allocation_history_helper.rb
module SlotAllocationHistoryHelper
end

app/helpers/slot_bookings_helper.rb
module SlotBookingsHelper
end

app/helpers/used_slots_helper.rb
module UsedSlotsHelper
end

app/views/first_entry_times/index.html.erb
<h1>First Entry Times for Vehicles</h1>
<table>
  <thead>
  <tr>
    <th>Vehicle Registration Number</th>
    <th>First Entry Time
    </th>
  </tr>
  </thead>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Park</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/slot_allocation_history/show.html.erb
<h1>Slot Allocation History for Vehicle: <%= @vehicle_registration_number %></h1>
<table>
  <thead>
  <tr>
    <th>Slot Number</th>
    <th>Entry Time</th>
  </tr>
  </thead>
  <tbody>
  <% @allocation_history.each do |slot_booking| %>
    <tr>
      <td><%= slot_booking.slot.number %></td>
      <td><%= slot_booking.entry_time.strftime('%Y-%m-%d %H:%M:%S') %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/slot_bookings/create.html.erb
<h1>SlotBookings#create</h1>
<p>Find me in app/views/slot_bookings/create.html.erb</p>

app/views/slot_bookings/new.html.erb
<%= form_with model: @slot_booking, url: slot_bookings_path, method: :post do |f| %>
  <%= f.label :entrance_number, 'Entrance Number/ID' %>
  <%= f.select :entrance_number, @entry_points.map { |ep| [ep.name, ep.id] }, prompt: 'Select an entry point' %>

  <%= f.label :vehicle_registration_number, 'Vehicle Registration Number' %>
  <%= f.text_field :vehicle_registration_number %>


  <%= f.label :entry_time, 'Entry Time' %>
  <%= f.datetime_select :entry_time, value: Date.today %>

  <%= f.submit 'Book Slot' %>
<% end %>

app/views/used_slots/index.html.erb
<%= form_tag(used_slots_path, method: :get) do %>
  <%= label_tag :selected_date, 'Select Date' %>
  <%= date_field_tag :selected_date, @selected_date %>
  <%= submit_tag 'Filter' %>
<% end %>

<h1>Used Slots on <%= @selected_date.strftime('%Y-%m-%d') %></h1>
<table>
  <thead>
  <tr>
    <th>Slot Number</th>
    <th>Vehicle Registration Number</th>
    <th>Entry Time</th>
  </tr>
  </thead>
  <tbody>
  <% @used_slots.each do |slot_booking| %>
    <tr>
      <td><%= slot_booking.slot.number %></td>
      <td><%= slot_booking.vehicle_registration_number %></td>
      <td><%= slot_booking.entry_time.strftime('%Y-%m-%d %H:%M:%S') %></td>
    </tr>
  <% end %>
  </tbody>
</table>